### ISSUE TITLE
Recipe-App: Kanban Board Setup

### ISSUE THREAD

**Issue by Adanzeakonobi** [Adanzeakonobi/Recipe-App#15]
- This [project](https://github.com/Adanzeakonobi/Recipe-App/projects/1) consists of two team, @Adanzeakonobi and @joshuaivie.

**Comment by omar-muhamad** [comment]
# Changes Required ♻️
### Hi @Adanzeakonobi and @joshuaivie,

Nice job, you are almost there.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## (Changes Required) Aspects to improve: ♻️

- [ ] There is one kanban card you missed adding points [pts] to it. Please fix that and keep in mind the number of points in the [Xpt] prefix. That number should indicate the number of points that show how complex the task is. 1 point = 1 hour of work.

![image](https://user-images.githubusercontent.com/68796232/187298348-390a258f-d5f6-4bf6-9dfa-da3d64e4aaee.png)

- [ ] There are two cards that you missed adding a description to it. So please fix that.

![image](https://user-images.githubusercontent.com/68796232/187298573-766df2f4-93ff-4897-9d49-691533fa9f86.png)

![image](https://user-images.githubusercontent.com/68796232/187298589-7135cb24-155c-493a-b3d1-665addd12f2c.png)


## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by mukhammadrizooff** [comment]
Hi @TEAM, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Optional suggestions

- [ ] [OPTIONAL] Please correct the project link in the issue description, there is an error!

![image](https://user-images.githubusercontent.com/63915024/187300580-6ab7f25b-a33b-496d-beb0-33b6c7cb9738.png)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Adanzeakonobi** [comment]
Thank You @mukhammadrizooff
